# -*- coding: utf-8 -*-
"""creditcard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2zMGldsRPMUgzocNuk2wLEdzTMaf_wk
"""

# import 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

data = pd.read_csv("/content/drive/MyDrive/creditcard/creditcard.csv")

data.head()

# 결측치 확인하기

data.isnull().sum()

# class label 확인하기

data['Class'].value_counts()

percent = (data['Class'].value_counts()[1] / data['Class'].value_counts()[0]) * 100
print(percent)

corr = data.corr()
fig = plt.figure(figsize = (24,24))

sns.heatmap(corr, vmax=1, square = True, annot = True, vmin=-1)
plt.show()

# seaborn scheme 로 세팅하고 font_scale 세팅.
plt.style.use('seaborn')
sns.set(font_scale=2.5)

# Commented out IPython magic to ensure Python compatibility.
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

# 브라우저에서 결과 바로 볼 수 있게 해줌.
# %matplotlib inline

# Time 하고 Amount를 살펴보자.

data['Time'].describe()

data['Amount'].describe()

